# Generated by Django 4.2.1 on 2023-07-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_carrito_itemcarrito_delete_user_carrito_productos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.IntegerField(choices=[(0, 'Debito'), (1, 'Credito'), (2, 'Visa/Nacional'), (3, 'Visa/Internacional')])),
            ],
        ),
    ]
